import pandas as pd
from openpyxl import load_workbook
from openpyxl.styles import PatternFill

# === Step 1: List of business names to match ===
business_names = [
    "Abraham Ash Realtors",
    "Achamizo & Co. Realty",
    "ADELA ANDERSON Realtors",
    "Adela Toranzo Realtors",
    "Adoracion Carrillo P.A. Realtors",
    "Adriana Cabanas Realtors",
    "AG Realty Brokers LLC",
    "Ahmanteri Group",
    "aim wealth realty",
    "Aio Realty & Property Manageme - Broker",
    "Alan Chocron Realtors",
    "Alejandra Avedano Realtors",
    "Alfa Realty Group - Broker",
    "Algebra International/GMAC Rea - Broker",
    "ALIGN RIGHT REALTY RIVERVIEW - Broker",
    "Alison Pusey Realtors",
    "All City Real Estate - Broker",
    "American Caribbean RE",
    "American Homes Realty Group - Broker",
    "American Paradise Prop Inc - Broker",
    "AMG INTERNATIONAL REALTY",
    "Amore Rodriguez Realtors",
    "Amorette Robertson, LLC Realtors",
    "Ana B. Cuan Realtors",
    "Ana M. Schnabel, P.A. Realtors",
    "Ana Maria McNatt Realtors",
    "Anabelle Marcano Sucre Realtors",
    "Ancona Real Estate Inc - Broker",
    "Andres Morales Realtors",
    "Angela Canete P.A. Realtors",
    "Angela Rincon Realtors",
    "Angie Rodriguez Realtors",
    "Anita Freud Realtors",
    "anja randegger Realtors",
    "Anthony Mannarino Realtors",
    "Antonio Omedas Realtors",
    "Ar Quinn Realty - Broker",
    "Arlet Quintana Lopez Realtors",
    "Ashley Jackson Realtors",
    "Autocarta Real Estate USA LLC - Global",
    "Avanti Way",
    "Avanti Way Realty",
    "Aventura Brokers LC Broker",
    "AVENTURA REAL ESTATE, Inc.---C - Broker",
    "Avisha Kassir Realtors",
    "Bailey Chalfont Realtors",
    "Beachfront Realty Inc - Broker",
    "Beatriz Cristina Arias Realtors",
    "Bee Realty Corp - Broker",
    "Beehouse Realty",
    "Ben Blue Realtors",
    "Benjamin Gluck Realtors",
    "Benjamin Rosen, P.A. Realtors",
    "Berkshire Hathaway HomeServices Florida",
    "Betania C Serrano G Realtors",
    "Beth Hinds Realtors",
    "Bettina Munoz Realtors",
    "BHHS EWM Realty",
    "Bianca Clay Realtors",
    "Blackbook Properties",
    "Blue Pen Real Estate, Inc",
    "Bozena Kaluza Realtors",
    "Brian Halstead Realtors",
    "Brian Sehmann Realtors",
    "Brian Smith Realtors",
    "Brickell Broker R.E. - Broker",
    "Brickell Realty group",
    "Brickell Realty Group, LLC",
    "Bridgestone Realty Llc - Broker",
    "BrokerNation Real Estate - Broker",
    "BROKERS LLC - Broker DONT REOPEN",
    "Brokers, LLC",
    "Brown Harris Stevens",
    "Business Name",
    "Camelot Professional Realtors - Broker",
    "Carlos Benavides Zapata Realtors",
    "Carlos Corredor Realtors",
    "Carlos E Beltran Realtors",
    "Carlos Felipe Contento, PA Realtors",
    "Carlos M Dominguez Realtors",
    "Carlos Sierra Torres Realtors",
    "Carmen Aguilera Realtors",
    "Carmen Freire Realtors",
    "Caroline Bertrand Realtors",
    "Carolyne Janvier Realtors",
    "Casabella Miami Realty - Broker",
    "Casalina Realty",
    "Cases Realty Group, Inc. - Broker",
    "Castellera Investments Inc - Broker",
    "Cem Turk Realtors",
    "Centeno International Realty LLC",
    "Century 21 BE3",
    "Century 21 Carioti",
    "CENTURY 21 New Millennium",
    "Century 21 Tenace Realty",
    "CERVERA REAL ESTATE, INC. - BROKER",
    "Chance Jewels Realtors",
    "Charles Rutenberg Realty Fort Lauderdale",
    "CHARLES RUTENBERG REALTY,INC. - BROKER",
    "Chester Dowdy Realtors",
    "Chris Mitchell Evert Realtors",
    "Christina Fernandez Realtors",
    "Christina Kovacs - The Home Agency Realtors",
    "Christopher Rizzi Realtors",
    "CME Realty, LLC",
    "Cohen & Roth, LLC",
    "Coldwell Banker",
    "Coldwell Banker Realty",
    "Colombia Margarita Mejia Realtors",
    "Complete Realty Group",
    "Consuelo Villacis Fajardo Realtors",
    "Cristina Soler Realtors",
    "Damelecia, Inc.",
    "Daniel Har Realtors",
    "Daniel Uribe | South Florida Realtors",
    "David Einy Realtors",
    "David Greenman Realtors",
    "David Lombardi Realtors",
    "David Ramirez Realtors",
    "Deal Flow Realty",
    "Deal Flow Realty LLC",
    "Delux Royal Real Estate, llc",
    "Denise Erickson Realtors",
    "Dezer Platinum Realty LLC - Broker",
    "DHL",
    "Diana Hernandez Realtors",
    "Diego Ramos Realtors",
    "DK International Realty, Inc",
    "Donohue Real Estate",
    "Douglas Elliman",
    "Douglas Elliman Florida",
    "Dumonde Consulting Group",
    "E M SQUARED REAL ESTATE LAB LLC",
    "Eaton Realty - Broker",
    "Eddie Schlackman Realtors",
    "Edmund Prieto Realtors",
    "Eliana Canan Realtors",
    "Elite International Realty - Broker",
    "Elite Ocean View Realty Llc - Broker",
    "Elite Sales Group - Broker",
    "Elizabeth Garrido Realtors",
    "Elizabeth Wemhoff Realtors",
    "Emerald Enterprises",
    "Engel & Volkers Americas, Inc",
    "Epic Capital Realty",
    "Equity Edge Realty Inc - Broker",
    "ERIKA L SALCEDO - Real Estate Broker Realtors",
    "Ernesto Avila Realtors",
    "Esha Desai Realtors",
    "Eva Mucho PA Realtors",
    "eXp Realty",
    "EXP REALTY LLC, FL - Broker",
    "Fabian Gonzalez Realtors",
    "Faith International Real Estate",
    "Falcon Empire Realty - Broker",
    "Fernando Alves Realtors",
    "First Brickell, LLC",
    "First Class Real State, LLC",
    "First Service Realty ERA",
    "Flora Nwalupue Realtors",
    "Florida Luxurious Properties LLC - Brok",
    "Florida Realty Investments - Broker",
    "Florida Realty of Miami",
    "FLORIDA REALTY OF MIAMI, CORP - Broker",
    "Floridian First Realty",
    "Fort Myers Beach Realty - Broker",
    "Fortex Realty",
    "FORTUNE CHRISTIE'S INTERNATIONAL REAL",
    "Fortune International Realty",
    "Frank Lustig Realtors",
    "Franklin Wollmann Realtors",
    "Gabriela Aparicio Realtors",
    "Gabriela de Marinis Realtors",
    "Galit Yosipovitch Realtors",
    "Gamal Riquelme Realtors",
    "Geane Brito Realtors",
    "George Depina Realtors",
    "Gerardo Gonzalez Realtors",
    "Gina Mentado Realtors",
    "Gina Robichaux Realtors",
    "Gladys Margarita Diaz Realtors",
    "Glenn Rivera Realtors",
    "Golden Keys Inc - Broker",
    "Got Florida Realty",
    "Graciela Gamardo-Lipsey Realtors",
    "Grand Living Realty",
    "Grehyni Narvaez Realtors",
    "Grove Town Properties, Inc. - Broker",
    "Haldeman Realty & Management",
    "Hana Binyamin Realtors",
    "Hanoi De La Cruz Boschini Realtors",
    "Hayley Dodge Realtors",
    "Hernan Golod Realtors",
    "Howard Chase Realtors",
    "Hugo Barragan LLC",
    "Huntington & Ellis, A Real Estate",
    "I Love Mi Casa Realty",
    "Icon Realty Brokerage",
    "ILLUSTRATED PROPERTIES",
    "Influencers Realty Group LLC",
    "Interinvestments Realty, Inc. - Broker",
    "International Realtors Group Corp.",
    "InvesTeam Realty - Broker",
    "Iraima Diaz Realtors",
    "Iris Rengel Realtors",
    "IRYNA VELYCHKO Realtors",
    "Ivelisse Zaitman Realtors",
    "Janet Tralins Realtors",
    "Janni Bonnatti Realtors",
    "Jaquelyn Bravo Realtors",
    "Jayanie Sherwood Realtors",
    "Jean Nayar Realtors",
    "Jenny Horn Realtors",
    "Jeremy Howard Realtors",
    "JESSIKA GOMEZ Realtors",
    "JFA Realty",
    "JJ Snow Hansen Realtors",
    "Joan Bruggink Realtors",
    "JoAnne Jones Realtors",
    "John Charles Realtors",
    "Jonathan Alfonso Realtors",
    "Jordan Sorman Realtors",
    "Jordana Tobel Realtors",
    "JORGE A. DE LOS RIOS Realtors",
    "jorge brito Realtors",
    "Jorge Guanche Realtors",
    "JOSE FELIX RIVAS Realtors",
    "Jose Rangel Laguna Realtors",
    "Jose Rodriguez Realtors",
    "Joseph Khalil Realtors",
    "Juan Carlos Bernal Realtors",
    "Juan Pablo Sierra Realtors",
    "Julian C. Delaney, PhD Realtors",
    "Julies Realty, Llc",
    "Juliet Ferrara Realtors",
    "Julio Masias Realtors",
    "Karen Sklawer Realtors",
    "Katerina Garcia Realtors",
    "Keller Williams Coral Gables - Broker",
    "Keller Williams Legacy - Broker",
    "KELLER WILLIAMS ON THE WATER",
    "KELLER WILLIAMS REALTY",
    "KELLER WILLIAMS REALTY - Broker",
    "KELLER WILLIAMS REALTY PROFESSIONALS",
    "Kleros Realty",
    "Krista Richman Realtors",
    "Labrada Realty",
    "Lana Perez Realtors",
    "Lang Realty, Inc.",
    "Laurie Finkelstein Reader Team",
    "Layer 7 Group - Broker",
    "Lennin Arias Florez Realtors",
    "Leonard Spivak Realtors",
    "Levine Realty Inc. - Broker",
    "Li Bensimon Realtors",
    "Lifestyle International Realty, Llc - B",
    "Lina Buitrago Realtors",
    "Linda Schechter Realtors",
    "Lisa Blake Realtors",
    "Lissette Ludmir Realtors",
    "lokation",
    "LoKation Real Estate - Broker",
    "London Foster Realty - Broker",
    "LPT REALTY LLC - Broker",
    "Lucas Gomez Realtors",
    "Lupita Alonso Realtors",
    "Luxe Living Realty - Broker",
    "Luxe Realty Group Llc - Broker",
    "Luxury Living Realty",
    "Lydia Azout Realtors",
    "M. Sean Reichert Realtors",
    "Mack1 Realty Group",
    "Madeleine Romanello Realtors",
    "Magela Rodriguez Realtors",
    "Marc Oliver Heinen Realtors",
    "Marcus Minyan Realtors",
    "Marcy Kaplan Realtors",
    "Maria Davila Galindo Patino Realtors",
    "Maria Macias Realtors",
    "Marlily Macareno Realtors",
    "Martha Gutierrez Realtors",
    "Martina Kanianska Realtors",
    "Marvin Torres Realtors",
    "Marysabel Mora Gutierrez Realtors",
    "Matias Cutuli Realtors",
    "MDS Real Estate Services, LLC - Broker",
    "Melange Real Estate",
    "Melissa Rubin Realtors",
    "Melissa Vianni Realtors",
    "Mercedes M Bravo Acosta Realtors",
    "Mercedes Osio Realtors",
    "Mia Realty, Corp. - Broker",
    "Miami New Realty - Broker",
    "Miami Realty Solution Group - Broker",
    "Michael Fediw Realtors",
    "Michael P. Schnabel Realtors",
    "Michelle De Pinto Realtors",
    "Migdey Castro Realtors",
    "Milagros Aspillaga Realtors",
    "Miles Goldstein Real Estate",
    "Million And Up Realty - Broker",
    "Miltiadis Kastanis Realtors",
    "Minette Schwartz Realtors",
    "Mirela Feliciano, Agent Realtors",
    "Miriam Fink Realtors",
    "Monica Rich Professional Real Estate",
    "MS Realty Services, LLC",
    "Natalie Ortega Realtors",
    "Nations Bancorp Realty LLC",
    "NB Elite Realty",
    "Nelcida Chakoff Realtors",
    "Nest Seekers Florida LLC",
    "Nest Seekers International - NY",
    "Nicole Castro Realtors",
    "Niki Higgins Realtors",
    "Nizz Realty Inc. - Broker",
    "Norka Realty Inc - Broker",
    "NRT-Florida",
    "NRT-Mid-Atlantic",
    "Olimpia Zanardi Realtors",
    "ONE Sotheby's International Realty",
    "One Sotheby's International Realty -",
    "ONE SOTHEBYS INTL. REALTY",
    "One Stop Realty Center",
    "One World Properties - Broker",
    "Onix Miranda Realtors",
    "Pacheco International Realty LLC",
    "Padovan Realty Corp.",
    "Palms Castles Realty",
    "Pamela Diaz-de-Leon Realtors",
    "Paradise Real Estate International - Br",
    "Parrot Realty LLC - Broker",
    "Parsiani Real Estate - Broker",
    "Patricia Delinois Realtors",
    "Patricia Martinez Cue Realtors",
    "Paul Sasseville Realtors",
    "Pavel Gonzalez Realtors",
    "Peter J Ruiz Realtors",
    "Peter Prudenzano PA MBA LCAM Realtors",
    "Pilar Aparicio Realtors",
    "Portico 56 Realty Group, LLC",
    "Potential Property Group",
    "Premier Agent Network",
    "Premier Elite Realty",
    "Premier Realty Firm, Corp",
    "Prime Real Estate Of Florida Llc - Brok",
    "Properties &c.",
    "Rachel Williams Realtors",
    "Raquel Abad Realtors",
    "Raul Bernal Realtors",
    "Re Florida Homes, Llc",
    "RE/MAX Advance Realty",
    "RE/MAX Premium Homes",
    "Reaction Realty Group, Inc.",
    "REAL BROKER LLC",
    "Real Estate Factory of S. Flor",
    "Real Estate Sales Force - Broker",
    "Real Estate Sales Intl Inc",
    "Real Estate TeamMates - Broker",
    "Reality Realty & Associates Llc - Broker",
    "Realty Home Advisors Inc - Broker",
    "Realty Hub - Broker",
    "Realty One Group Evolution",
    "Redfin",
    "Redfin Corporation",
    "Regency Realty Services - Broker",
    "Related ISG Int'l Realty, LLC. - Broker",
    "ReMax Estate Properties",
    "Renzo Lamela Realtors",
    "Results Realty of Dade County - Broker",
    "Rising Realty Of S Florida - Broker",
    "Rita Segura Realtors",
    "Robert Kotelsky Realtors",
    "Robert Slack LLC",
    "ROBERT SLACK LLC - Broker",
    "Roberto Bracho Realtors",
    "Rockstar International Realty",
    "RODTELL REALTY CORP.",
    "Roman's Pro Realty",
    "Rosa Napolitano Realtors",
    "ROY LEMUS Realtors",
    "Royal Dream Realty Corp - Broker",
    "Royal Residence Realty",
    "Saca's Realty, Inc",
    "Sandra Monteverde Realtors",
    "Sandra Paletta Realtors",
    "Sarahy Yanez Realtors",
    "Scott Diffenderfer Realtors",
    "Scuttina Signature Real Estate Group,",
    "Sebastian Garcia, PA, MSIRE Realtors",
    "Sebastian Golod Realtors",
    "Sebastien Sabet Realtors",
    "SERHANT.",
    "Sharon Razla Realtors",
    "Sharpline Realty Inc",
    "Shelton And Stewart Realtor - Broker",
    "shlomo manor Realtors",
    "Silmara Cicciarelli Realtors",
    "Silvia Veronica Sassetti Realtors",
    "Simon Molero Avila Realtors",
    "Sky Gillespie Realtors",
    "Sky International Realty - Broker",
    "SMITH Associates - Broker",
    "Soar Realty Corp",
    "Sol Realty LLC - Broker",
    "Sonia Conserva Realtors",
    "Soraia Farah Realtors",
    "South Florida Residential Realty, Inc.",
    "Stacy Schiano Realtors",
    "Stephanie Penaherrera Realtors",
    "Stephanie Ubeda Realtors",
    "Stephen Heck Realtors",
    "Steven Vena Realtors",
    "Stratwell, LLC",
    "Susana Kenigsberg Realtors",
    "SYKES",
    "Sync Brokerage INC.",
    "Tag Real Estate",
    "Team Khemlani Realtors",
    "Thays Del Valle Alvarez Realtors",
    "The Agency Florida LLC - Broker",
    "The Cardona Group / DACAM",
    "The Corcoran Group",
    "The Cuadra Group",
    "The GlobalVest Group LLC",
    "The Keyes Company - Broker",
    "The Lab Realty Group, LLC - Broker",
    "THE TABLE - Broker",
    "The Valenzuela Real Estate Group",
    "Thomas Marrazza Realtors",
    "Todd Nordstrom Realtors",
    "TREND REALTY - Broker",
    "Trident Real Estate, Inc",
    "Trust Properties USA FL, Inc. - Broker",
    "Trustpoint Realty, LLC. - Broker",
    "United Realty Group",
    "United Realty Group Inc.- Broker",
    "Urban Resource",
    "Vavra Realty 1947",
    "Vené Giufurta Realtors",
    "Vicky Rua Realtors",
    "Victor A Ruiz Realtors",
    "Vision Miami Re Analytical Inv - Broker",
    "Vivian Toppe Realtors",
    "West Avenue Realty - Broker",
    "William Blaikie Realtors",
    "William Hobbs Realtors",
    "Winsome Realty",
    "World Renowned Real Estate",
    "Xcellence Realty Inc. - Broker",
    "Yaffe International Realty - Broker",
    "Yannick Alessio Realtors",
    "Yare Diaz Realtors",
    "Yoni Dahan Realtors",
    "Yulissa Fontanez Realtors"
]


# === Step 2: Read CSV file ===
input_file = "lead_2.csv"
output_file = "lead_2_highlighted.xlsx"

df = pd.read_csv(input_file)

# === Step 3: Detect the column with business names ===
name_col = [col for col in df.columns if "business" in col.lower()][0]

# === Step 4: Mark matches ===
df["Matched"] = df[name_col].isin(business_names)

# === Step 5: Move matched rows to the top ===
df = df.sort_values(by="Matched", ascending=False).reset_index(drop=True)

# === Step 6: Save to Excel first (since CSV can’t store colors) ===
df.to_excel(output_file, index=False)

# === Step 7: Color matched rows ===
wb = load_workbook(output_file)
ws = wb.active

highlight = PatternFill(start_color="FFF9C4", end_color="FFF9C4", fill_type="solid")  # yellow

# Find the column index of "Matched"
matched_col_index = df.columns.get_loc("Matched") + 1  # Excel is 1-based

for row in range(2, ws.max_row + 1):
    if ws.cell(row=row, column=matched_col_index).value:  # True if matched
        for col in range(1, len(df.columns) + 1):
            ws.cell(row=row, column=col).fill = highlight

wb.save(output_file)
print(f"✅ Highlighted file saved as '{output_file}' (matched rows on top)")
